### ISSUE TITLE
Accessing from explorervia context menu for simpler access

### ISSUE THREAD

**Issue by ColonelBuendia** [vivainio/RoughGrep#3]
I have found this be really useful when I am not already using the command line - any thoughts on including an option to make it easier to have context menu integration?  

For my setup, only on folders, I implemented like this from a batch file:

```
@echo off
SET rggPath=C:\pathto\yourcopyof\rgg.exe
 
rem add it for folders
@reg add "HKEY_CLASSES_ROOT\Folder\shell\rough grep"         /t REG_SZ /v "" /d "rough grep"   /f
@reg add "HKEY_CLASSES_ROOT\Folder\shell\rough grep"         /t REG_EXPAND_SZ /v "Icon" /d "%rggPath%,0" /f
@reg add "HKEY_CLASSES_ROOT\Folder\shell\rough grep\command" /t REG_SZ /v "" /d "%rggPath% \"%%1\"" /f
pause
```

**Comment by vivainio** [comment]
Thanks for the idea. Maybe —install command line arg could set this up

**Comment by vivainio** [comment]
Thanks for the suggestion, "rgg --install" is now in v2.9 release

**Comment by ColonelBuendia** [comment]
thanks for building a useful tool!
